import grpc
import ${{ package_id }}


class ${{ service_name }}${{ service_name_postfix }}(${{ package_id }}.${{ service_name }}${{ service_name_parent_postfix }}):
    # <auto-generated>
    ${{ service_source_code }}
    # </auto-generated>
