[project]
name = "${{ service_name_lower }}-service-sdk"
version = "1.0.0"
dependencies = [
    "grpcio >= 1.57.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
