/**
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef VELOCITAS_SERVICE_IMPL_${{ service_name }}_H
#define VELOCITAS_SERVICE_IMPL_${{ service_name }}_H

#include <grpc/grpc.h>
#include <${{ grpc_service_header_path }}>

namespace velocitas {

class ${{ service_name_camel_case }}Service final : public ${{ package_id }}::${{ service_name }}::Service {
public:
    ${{ service_name_camel_case }}Service() = default;
    virtual ~${{ service_name_camel_case }}Service() {};

// <auto-generated>
${{ service_header_code }}
// </auto-generated>

// <user-defined>
${{ service_header_user_code }}
// </user-defined>
};

} // namespace velocitas

#include "${{ service_name_camel_case }}ServiceImpl.cpp"

#endif // VELOCITAS_SERVICE_IMPL_${{ service_name }}_H
